"""
Django settings for cuestonario project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#=)y&o81@kdy)to2)l=t8lbq4!3l%x-psd*&0um!_fd16kvc%2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'leaflet',
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cuestonario.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cuestonario.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db_prueba',
        'USER': 'prueba',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logs
"""
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/cuestionario.log',
            'formatter': 'verbose'
        },
        'file_oxxo': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/evaluaciones_oxxo.log',
            'formatter': 'verbose'
        },
        'file_seven': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/evaluaciones_seven.log',
            'formatter': 'verbose'
        },
        'file_as': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/evaluaciones_as.log',
            'formatter': 'verbose'
        },
        'db_logging': {
            'level' : 'INFO',
            'class': 'logging.FileHandler',
            #'backupCount' : 5,
            #'maxBytes': 5000000,
            'filename': '/tmp/evaluaciones_db.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'django.db' : {
            'handlers' : ['db_logging'],
            'level' : 'DEBUG',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'evaluaciones': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'seven': {
            'handlers': ['file','file_seven'],
            'level': 'DEBUG',
        },
        'general': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'autoservicio': {
            'handlers': ['file','file_as'],
            'level': 'DEBUG',
        },
        'documentos': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'alee': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'oxxo': {
            'handlers': ['file','file_oxxo'],
            'level': 'DEBUG',
        },
        'siem': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'adf': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'autentificacion': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        #'autentificacion': {
        #    'handlers': ['file'],
        #    'level': 'DEBUG',
        #},
    }
    }
    """